CREATE TABLE ORDERS( 
  ID integer,
  ORDER_ID varchar2(20),
  CREATE_DATE timestamp,
  CUSTOMER_ID integer  
);

ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_ID_PK PRIMARY KEY (ID) ENABLE;

CREATE SEQUENCE ORDERS_SEQ START WITH 1;
ALTER SEQUENCE ORDERS_SEQ NOCACHE;